//
//  DNSType.h
//  DNS
//
//  Created by Victor Gama on 11/10/2018.
//  Copyright © 2018 Victor Gama. All rights reserved.
//

#ifndef DNSType_h
#define DNSType_h

// Ref. https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4

typedef NS_ENUM(uint16_t, DNSType) {
    DNSTypeA                      = 1,
    DNSTypeNS                     = 2,
    DNSTypeMD                     = 3,
    DNSTypeMF                     = 4,
    DNSTypeCNAME                  = 5,
    DNSTypeSOA                    = 6,
    DNSTypeMB                     = 7,
    DNSTypeMG                     = 8,
    DNSTypeMR                     = 9,
    DNSTypeNULL                   = 10,
    DNSTypeWKS                    = 11,
    DNSTypePTR                    = 12,
    DNSTypeHINFO                  = 13,
    DNSTypeMINFO                  = 14,
    DNSTypeMX                     = 15,
    DNSTypeTXT                    = 16,
    DNSTypeRP                     = 17,
    DNSTypeAFSDB                  = 18,
    DNSTypeX25                    = 19,
    DNSTypeISDN                   = 20,
    DNSTypeRT                     = 21,
    DNSTypeNSAP                   = 22,
    DNSTypeNSAPPtr                = 23,
    DNSTypeSIG                    = 24,
    DNSTypeKEY                    = 25,
    DNSTypePX                     = 26,
    DNSTypeGPOS                   = 27,
    DNSTypeAAAA                   = 28,
    DNSTypeLOC                    = 29,
    DNSTypeNXT                    = 30,
    DNSTypeEID                    = 31,
    DNSTypeNIMLOC                 = 32,
    DNSTypeSRV                    = 33,
    DNSTypeATMA                   = 34,
    DNSTypeNAPTR                  = 35,
    DNSTypeKX                     = 36,
    DNSTypeCERT                   = 37,
    DNSTypeA6                     = 38,
    DNSTypeDNAME                  = 39,
    DNSTypeSINK                   = 40,
    DNSTypeOPT                    = 41,
    DNSTypeAPL                    = 42,
    DNSTypeDS                     = 43,
    DNSTypeSSHFP                  = 44,
    DNSTypeIPSECKey               = 45,
    DNSTypeRRSIG                  = 46,
    DNSTypeNSEC                   = 47,
    DNSTypeDNSKEY                 = 48,
    DNSTypeDHCID                  = 49,
    DNSTypeNSEC3                  = 50,
    DNSTypeNSEC3Param             = 51,
    DNSTypeTLSA                   = 52,
    DNSTypeSMIMEA                 = 53,
    // Unassigned                   = 54,
    DNSTypeHIP                    = 55,
    DNSTypeNINFO                  = 56,
    DNSTypeRKEY                   = 57,
    DNSTypeTALINK                 = 58,
    DNSTypeCDS                    = 59,
    DNSTypeCSNSKey                = 60,
    DNSTypeOpenPGPKey             = 61,
    DNSTypeCSync                  = 62,
    // Unassigned                   = 63-98,
    DNSTypeSPF                    = 99,
    DNSTypeUINFO                  = 100,
    DNSTypeUID                    = 101,
    DNSTypeGID                    = 102,
    DNSTypeUNSPEC                 = 103,
    DNSTypeNID                    = 104,
    DNSTypeL32                    = 105,
    DNSTypeL64                    = 106,
    DNSTypeLP                     = 107,
    DNSTypeEUI48                  = 108,
    DNSTypeEUI64                  = 109,
    // Unassigned                   = 110-248,
    DNSTypeTKEY                   = 249,
    DNSTypeTSIG                   = 250,
    DNSTypeIXFR                   = 251,
    DNSTypeAXFR                   = 252,
    DNSTypeMAILB                  = 253,
    DNSTypeMAILA                  = 254,
    DNSTypeAny                    = 255,
    DNSTypeURI                    = 256,
    DNSTypeCAA                    = 257,
    DNSTypeAVC                    = 258,
    DNSTypeDOA                    = 259,
    // Unassigned                   = 260-32767,
    DNSTypeTA                     = 32768,
    DNSTypeDLV                    = 32769,
    // Unassigned                   = 32770-65279,
    // Private Use                  = 65280-65534,
    DNSTypeReserved               = 65535,
};


#endif /* DNSType_h */
